/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.johnandrade.reto5.vista;

import com.johnandrade.reto5.controlador.ControladorRequerimientos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author johna
 */
public class VistaRequerimientosUI extends javax.swing.JFrame {
    
    private ControladorRequerimientos controlador;
    private Consulta1TM consulta1TM;
    private Consulta2TM consulta2TM;
    private Consulta3TM consulta3TM;
    

    /**
     * Creates new form VistaRequerimientosUI
     */
    public VistaRequerimientosUI() {
        controlador = new ControladorRequerimientos();
        initComponents();
        listarConsulta1();
        listarConsulta2();
        listarConsulta3();
        setLocationRelativeTo(null);
    }

    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("com/johnandrade/reto5/images/logo.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPrincipal = new javax.swing.JTabbedPane();
        pConsulta1 = new javax.swing.JPanel();
        JpanelTable = new javax.swing.JScrollPane();
        tblConsulta1 = new javax.swing.JTable();
        pConsulta2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsulta2 = new javax.swing.JTable();
        pConsulta3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsulta3 = new javax.swing.JTable();
        miMenu = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();
        mVentanas = new javax.swing.JMenu();
        mConsulta1 = new javax.swing.JMenuItem();
        mConsulta2 = new javax.swing.JMenuItem();
        mConsulta3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto 5 Grupo 47");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName("Principal"); // NOI18N

        tpPrincipal.setMinimumSize(new java.awt.Dimension(600, 400));

        pConsulta1.setLayout(new java.awt.BorderLayout());

        tblConsulta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lider", "Cargo", "Proyectos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JpanelTable.setViewportView(tblConsulta1);
        if (tblConsulta1.getColumnModel().getColumnCount() > 0) {
            tblConsulta1.getColumnModel().getColumn(0).setResizable(false);
            tblConsulta1.getColumnModel().getColumn(1).setResizable(false);
            tblConsulta1.getColumnModel().getColumn(2).setResizable(false);
        }

        pConsulta1.add(JpanelTable, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Consulta 1", pConsulta1);

        pConsulta2.setLayout(new java.awt.BorderLayout());

        tblConsulta2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Material", "Nombre Material", "Cantidad", "Precio x unidad", "Precio Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblConsulta2);
        if (tblConsulta2.getColumnModel().getColumnCount() > 0) {
            tblConsulta2.getColumnModel().getColumn(0).setResizable(false);
            tblConsulta2.getColumnModel().getColumn(1).setResizable(false);
            tblConsulta2.getColumnModel().getColumn(2).setResizable(false);
            tblConsulta2.getColumnModel().getColumn(3).setResizable(false);
            tblConsulta2.getColumnModel().getColumn(4).setResizable(false);
        }

        pConsulta2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Consulta 2", pConsulta2);

        pConsulta3.setLayout(new java.awt.BorderLayout());

        tblConsulta3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Proyecto", "Ciudad", "Clasificacion", "Costo Proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblConsulta3);
        if (tblConsulta3.getColumnModel().getColumnCount() > 0) {
            tblConsulta3.getColumnModel().getColumn(0).setResizable(false);
            tblConsulta3.getColumnModel().getColumn(1).setResizable(false);
            tblConsulta3.getColumnModel().getColumn(2).setResizable(false);
            tblConsulta3.getColumnModel().getColumn(3).setResizable(false);
        }

        pConsulta3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Consulta 3", pConsulta3);

        getContentPane().add(tpPrincipal, java.awt.BorderLayout.CENTER);
        tpPrincipal.getAccessibleContext().setAccessibleName("Consulta 1");

        mArchivo.setText("Archivo");

        mSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mArchivo.add(mSalir);

        miMenu.add(mArchivo);

        mVentanas.setText("Ventanas");

        mConsulta1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mConsulta1.setText("Consulta 1");
        mConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsulta1ActionPerformed(evt);
            }
        });
        mVentanas.add(mConsulta1);

        mConsulta2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mConsulta2.setText("Consulta 2");
        mConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsulta2ActionPerformed(evt);
            }
        });
        mVentanas.add(mConsulta2);

        mConsulta3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mConsulta3.setText("Consulta 3");
        mConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsulta3ActionPerformed(evt);
            }
        });
        mVentanas.add(mConsulta3);

        miMenu.add(mVentanas);

        setJMenuBar(miMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsulta2ActionPerformed
        tpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_mConsulta2ActionPerformed

    private void mConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsulta1ActionPerformed
        tpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_mConsulta1ActionPerformed

    private void mConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsulta3ActionPerformed
        tpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_mConsulta3ActionPerformed

     public void exit_app(){
         if (JOptionPane.showConfirmDialog(this, "Desea cerrar la aplicacion",getTitle(),JOptionPane.YES_OPTION)== JOptionPane.YES_OPTION) {
             dispose();
        }
    }
    
    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
       exit_app();
    }//GEN-LAST:event_mSalirActionPerformed

    private void listarConsulta1(){
        try {
            var registrosBS = controlador.consultarRequerimiento1();
            consulta1TM = new Consulta1TM(registrosBS);
            tblConsulta1.setModel(consulta1TM);
        } catch (Exception e) {
        }
    }
    private void listarConsulta2(){
        try {
            var registrosBS2 = controlador.consultarRequerimiento2();
            consulta2TM = new Consulta2TM(registrosBS2);
            tblConsulta2.setModel(consulta2TM);
        } catch (Exception e) {
        }
    }
    private void listarConsulta3(){
        try {
            var registrosBS3 = controlador.consultarRequerimiento3();
            consulta3TM = new Consulta3TM(registrosBS3);
            tblConsulta3.setModel(consulta3TM);
        } catch (Exception e) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRequerimientosUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JpanelTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenuItem mConsulta1;
    private javax.swing.JMenuItem mConsulta2;
    private javax.swing.JMenuItem mConsulta3;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenu mVentanas;
    private javax.swing.JMenuBar miMenu;
    private javax.swing.JPanel pConsulta1;
    private javax.swing.JPanel pConsulta2;
    private javax.swing.JPanel pConsulta3;
    private javax.swing.JTable tblConsulta1;
    private javax.swing.JTable tblConsulta2;
    private javax.swing.JTable tblConsulta3;
    private javax.swing.JTabbedPane tpPrincipal;
    // End of variables declaration//GEN-END:variables
}
